#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# install_hardware.sh — Build and install hardware-specific C++ SDK bindings.
#
# Usage:
#   conda activate lerobot
#   bash install_hardware.sh --arx5
#   bash install_hardware.sh --flexiv
#   bash install_hardware.sh --pico4
#   bash install_hardware.sh --xense
#   bash install_hardware.sh --spacemouse
#   bash install_hardware.sh --all
#
# Each flag is independent — rerun any single module without touching others.
#
# Environment variables:
#   RDK_INSTALL_PATH   Path to Flexiv RDK installation (default: ~/rdk_install)
# ---------------------------------------------------------------------------

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR"

# ── Guards ───────────────────────────────────────────────────────────────────

check_conda() {
    if [[ -z "${CONDA_PREFIX:-}" ]]; then
        echo "ERROR: No conda environment is active. Please activate first:"
        echo "  conda activate lerobot"
        exit 1
    fi
    echo "Using conda env: ${CONDA_DEFAULT_ENV:-} ($CONDA_PREFIX)"
}

# ── Shared helpers ────────────────────────────────────────────────────────────

# Write sitecustomize.py that preloads conda's libstdc++ at Python startup.
# Required by C++ extensions compiled with GCC 14+ (ARX5, flexiv_rt) so they
# can find CXXABI_1.3.15 symbols without relying on the older system libstdc++.
write_sitecustomize() {
    local PY_VER
    PY_VER="$(python -c 'import sys; print(f"python{sys.version_info.major}.{sys.version_info.minor}")')"
    local SITE_DIR="${CONDA_PREFIX}/lib/${PY_VER}/site-packages"
    local TARGET="${SITE_DIR}/sitecustomize.py"

    if [[ -f "$TARGET" ]] && grep -q "RTLD_GLOBAL" "$TARGET" 2>/dev/null; then
        echo "[sitecustomize] Already configured."
        return
    fi
    echo "[sitecustomize] Writing libstdc++ preloader → $TARGET"
    cat > "$TARGET" << 'PYEOF'
"""
Preload conda's libstdc++ so C++ extensions compiled with GCC 14+ can find
CXXABI_1.3.15 symbols without relying on the system's older libstdc++.
Auto-generated by install_hardware.sh.
"""
import ctypes
import os

prefix = os.environ.get("CONDA_PREFIX")
if prefix:
    p = os.path.join(prefix, "lib", "libstdc++.so.6")
    if os.path.exists(p):
        try:
            ctypes.CDLL(p, mode=ctypes.RTLD_GLOBAL)
        except Exception:
            pass
PYEOF
}

# conda installs a udev/ directory that confuses ctypes.util.find_library("udev"),
# causing pyudev/xensesdk to crash with "OSError: .../lib/udev: Is a directory".
fix_udev_discovery() {
    if [[ -d "${CONDA_PREFIX}/lib/udev" ]]; then
        echo "[udev] Renaming ${CONDA_PREFIX}/lib/udev to avoid pyudev clash..."
        local target="${CONDA_PREFIX}/lib/udev.rules.d"
        [[ -e "$target" ]] && target="${target}.bak.$(date +%s)"
        mv "${CONDA_PREFIX}/lib/udev" "$target" || true
    fi
    if [[ -e "${CONDA_PREFIX}/lib/libudev.so.1" && ! -e "${CONDA_PREFIX}/lib/libudev.so" ]]; then
        ln -s libudev.so.1 "${CONDA_PREFIX}/lib/libudev.so" || true
    fi
}

# ── Module: ARX5 ─────────────────────────────────────────────────────────────

install_arx5() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " ARX5 SDK  →  pyarx"
    echo "══════════════════════════════════════════"

    local SDK_DIR="$PROJECT_ROOT/third_party/ARX5_SDK"
    if [[ ! -d "$SDK_DIR" ]]; then
        echo "ERROR: $SDK_DIR not found."
        echo "  Run: git submodule update --init third_party/ARX5_SDK"
        return 1
    fi

    # The PyPI spdlog package installs conflicting C++ headers — remove it first.
    pip uninstall -y spdlog 2>/dev/null || true

    bash "$SDK_DIR/build_python.sh"

    # ARX5 SDK requires cap_sys_nice for real-time thread scheduling.
    local PYTHON_BIN
    PYTHON_BIN="$(readlink -f "$(which python)")"
    echo "[arx5] Setting cap_sys_nice on $PYTHON_BIN"
    sudo setcap cap_sys_nice=ep "$PYTHON_BIN"

    write_sitecustomize
    echo "[arx5] Done. Verify with: python -c 'import pyarx; print(pyarx)'"
}

# ── Module: Flexiv ────────────────────────────────────────────────────────────

install_flexiv() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " libpyflexiv  →  flexiv_rt"
    echo "══════════════════════════════════════════"

    local LIB_DIR="$PROJECT_ROOT/third_party/libpyflexiv"
    local RDK_INSTALL="${RDK_INSTALL_PATH:-$HOME/rdk_install}"

    if [[ ! -d "$LIB_DIR" ]]; then
        echo "ERROR: $LIB_DIR not found."
        echo "  Run: git submodule update --init third_party/libpyflexiv"
        return 1
    fi
    if [[ ! -d "$RDK_INSTALL" ]]; then
        echo "ERROR: Flexiv RDK not found at: $RDK_INSTALL"
        echo "  Download the RDK and install it there, or set RDK_INSTALL_PATH."
        return 1
    fi

    local BUILD_DIR="$LIB_DIR/build"
    rm -rf "$BUILD_DIR"

    cmake \
        -S "$LIB_DIR" \
        -B "$BUILD_DIR" \
        -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_PREFIX_PATH="$RDK_INSTALL;$CONDA_PREFIX" \
        -DCMAKE_BUILD_RPATH="$CONDA_PREFIX/lib" \
        -DCMAKE_INSTALL_RPATH="$CONDA_PREFIX/lib" \
        -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON \
        -DPYTHON_EXECUTABLE="$(which python)"

    cmake --build "$BUILD_DIR" -j"$(nproc)"

    "$(which pip)" install -e "$LIB_DIR" --no-build-isolation --quiet

    write_sitecustomize
    echo "[flexiv] Done. Verify with: python -c 'import flexiv_rt; print(flexiv_rt)'"
}

# ── Module: Pico4 ─────────────────────────────────────────────────────────────

install_pico4() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " XenseVR-PC-Service  →  xensevr_pc_service_sdk"
    echo "══════════════════════════════════════════"

    local SDK_SRC="$PROJECT_ROOT/third_party/XenseVR-PC-Service"
    local PYBIND_DIR="$PROJECT_ROOT/src/lerobot/teleoperators/pico4/xensevr-pc-service-pybind"

    if [[ ! -d "$SDK_SRC" ]]; then
        echo "ERROR: $SDK_SRC not found."
        echo "  Run: git submodule update --init third_party/XenseVR-PC-Service"
        return 1
    fi

    # Build the C SDK
    bash "$SDK_SRC/RoboticsService/PXREARobotSDK/build.sh"

    # Copy headers and .so into the pybind directory
    local CSDK_DIR="$SDK_SRC/RoboticsService/PXREARobotSDK"
    mkdir -p "$PYBIND_DIR/include" "$PYBIND_DIR/lib"
    cp "$CSDK_DIR/PXREARobotSDK.h" "$PYBIND_DIR/include/"
    cp -r "$CSDK_DIR/nlohmann" "$PYBIND_DIR/include/"
    cp "$CSDK_DIR/build/libPXREARobotSDK.so" "$PYBIND_DIR/lib/"

    # Build and install the Python bindings
    cd "$PYBIND_DIR"
    rm -rf build *.egg-info
    pip uninstall -y xensevr_pc_service_sdk 2>/dev/null || true
    "$(which pip)" install . --no-build-isolation --quiet

    echo "[pico4] Done. Verify with: python -c 'import xensevr_pc_service_sdk; print(xensevr_pc_service_sdk)'"
}

# ── Module: Xense ─────────────────────────────────────────────────────────────

install_xense() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " xensesdk + xensegripper (PyPI)"
    echo "══════════════════════════════════════════"

    fix_udev_discovery

    uv pip install xensesdk xensegripper
    # xensesdk requires a specific av version
    uv pip install av==15.1.0

    local PY_VER
    PY_VER="$(python -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"

    # onnxruntime-gpu uses dlopen() and ignores LD_LIBRARY_PATH — patch its RPATH.
    local ONNX_SO="${CONDA_PREFIX}/lib/python${PY_VER}/site-packages/onnxruntime/capi/libonnxruntime_providers_cuda.so"
    if [[ -f "$ONNX_SO" ]]; then
        echo "[xense] Fixing onnxruntime-gpu RPATH..."
        uv pip install patchelf --quiet
        patchelf --set-rpath "${CONDA_PREFIX}/lib" "$ONNX_SO"
        echo "[xense] RPATH set: $(patchelf --print-rpath "$ONNX_SO")"
    fi

    # OpenCV's bundled Qt plugin causes XCB errors inside conda envs.
    local QXCB="${CONDA_PREFIX}/lib/python${PY_VER}/site-packages/cv2/qt/plugins/platforms/libqxcb.so"
    if [[ -f "$QXCB" ]]; then
        echo "[xense] Removing OpenCV bundled Qt plugin: $QXCB"
        rm -f "$QXCB"
    fi

    echo "[xense] Done. Verify with: python -c 'import xensesdk; print(xensesdk)'"
}

# ── Module: SpaceMouse ────────────────────────────────────────────────────────

install_spacemouse() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " SpaceMouse — HID / udev setup"
    echo "══════════════════════════════════════════"

    if ! dpkg -l | grep -q "^ii.*libhidapi-dev"; then
        sudo apt-get update && sudo apt-get install -y libhidapi-dev
    else
        echo "[spacemouse] libhidapi-dev already installed."
    fi

    local UDEV_RULE="/etc/udev/rules.d/99-hidraw-permissions.rules"
    if [[ ! -f "$UDEV_RULE" ]]; then
        echo "[spacemouse] Adding udev rule for HID access..."
        echo 'KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0664", GROUP="plugdev"' \
            | sudo tee "$UDEV_RULE" > /dev/null
        sudo udevadm control --reload-rules
        sudo udevadm trigger
    else
        echo "[spacemouse] udev rule already exists."
    fi

    if ! groups "$USER" | grep -q plugdev; then
        sudo usermod -aG plugdev "$USER"
        echo "[spacemouse] WARN: Log out and back in for plugdev group to take effect."
    fi

    echo "[spacemouse] Done."
}

# ── Argument parsing ──────────────────────────────────────────────────────────

if [[ $# -eq 0 ]]; then
    cat << 'USAGE'
Usage: bash install_hardware.sh [OPTIONS]

Options:
  --arx5        Build pyarx        (ARX5 robot arm SDK bindings)
  --flexiv      Build flexiv_rt    (Flexiv Rizon4 RT bindings)
  --pico4       Build xensevr_pc_service_sdk  (Pico4 VR teleop)
  --xense       Install xensesdk + xensegripper from PyPI
  --spacemouse  Install HID / udev support for SpaceMouse
  --all         All of the above

Environment variables:
  RDK_INSTALL_PATH   Path to Flexiv RDK (default: ~/rdk_install)

Example:
  conda activate lerobot
  bash install_hardware.sh --arx5 --xense
  bash install_hardware.sh --all
USAGE
    exit 0
fi

check_conda

DO_ARX5=false
DO_FLEXIV=false
DO_PICO4=false
DO_XENSE=false
DO_SPACEMOUSE=false

for arg in "$@"; do
    case "$arg" in
        --arx5)       DO_ARX5=true ;;
        --flexiv)     DO_FLEXIV=true ;;
        --pico4)      DO_PICO4=true ;;
        --xense)      DO_XENSE=true ;;
        --spacemouse) DO_SPACEMOUSE=true ;;
        --all)
            DO_ARX5=true
            DO_FLEXIV=true
            DO_PICO4=true
            DO_XENSE=true
            DO_SPACEMOUSE=true
            ;;
        *)
            echo "ERROR: Unknown option: $arg"
            echo "Run 'bash install_hardware.sh' for usage."
            exit 1
            ;;
    esac
done

$DO_ARX5       && install_arx5
$DO_FLEXIV     && install_flexiv
$DO_PICO4      && install_pico4
$DO_XENSE      && install_xense
$DO_SPACEMOUSE && install_spacemouse

echo ""
echo "All done."
