#!/bin/bash

# Check the operating system
OS_NAME=$(uname -s)
OS_VERSION=""

if [[ "$OS_NAME" == "Linux" ]]; then
    if command -v lsb_release &>/dev/null; then
        OS_VERSION=$(lsb_release -rs)
    elif [[ -f /etc/os-release ]]; then
        . /etc/os-release
        OS_VERSION=$VERSION_ID
    fi
    # Tested on Ubuntu 22.04 (jammy) and 24.04 (noble). The host was upgraded
    # 22.04 → 24.04, which bumps the system toolchain to GCC 13 — fine because
    # the hardware SDKs build against the conda cross-compiler, not system GCC.
    if [[ "$OS_VERSION" != "22.04" && "$OS_VERSION" != "24.04" ]]; then
        echo "Warning: This script has only been tested on Ubuntu 22.04 and 24.04"
        echo "Your system is running Ubuntu $OS_VERSION."
        read -p "Do you want to continue anyway? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo "Installation cancelled."
            exit 1
        fi
    fi
else
    echo "Unsupported operating system: $OS_NAME"
    exit 1
fi

echo "Operating system check passed: $OS_NAME $OS_VERSION"

# Large PyPI wheels such as torch can exceed uv's default 30s timeout on
# slower links. Allow callers to override, but use a safer default for setup.
export UV_HTTP_TIMEOUT="${UV_HTTP_TIMEOUT:-300}"

# Resolve script directory so files can be referenced reliably
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}")"
PROJECT_ROOT="$SCRIPT_DIR"

# Conda environment yaml file (canonical name)
CONDA_ENV_FILE="$SCRIPT_DIR/conda_environment.yaml"
if [[ ! -f "$CONDA_ENV_FILE" ]]; then
    echo "Error: conda environment yaml not found: $CONDA_ENV_FILE"
    exit 1
fi

# ── Conda environment creation ────────────────────────────────────────────────

create_environment() {
    local CONDA_CMD=$1
    local ENV_NAME=$2

    # Deactivate current environment if any (use conda deactivate for both conda and mamba)
    conda deactivate 2>/dev/null || true

    # Remove existing environment if it exists
    if $CONDA_CMD env list | grep -q "^$ENV_NAME "; then
        echo "Removing existing environment '$ENV_NAME'..."
        if ! $CONDA_CMD env remove -n "$ENV_NAME" -y; then
            echo "Error: Failed to remove existing environment '$ENV_NAME'."
            return 1
        fi
    fi

    # Create new environment from conda_environment.yaml
    if ! $CONDA_CMD env create -f "$CONDA_ENV_FILE" -n "$ENV_NAME"; then
        echo "Error: Failed to create $CONDA_CMD environment '$ENV_NAME' from: $CONDA_ENV_FILE"
        return 1
    fi

    echo "$CONDA_CMD environment '$ENV_NAME' created from: $CONDA_ENV_FILE"

    echo -e "[INFO] Created $CONDA_CMD environment named '$ENV_NAME'.\n"
    echo -e "\t\t1. To activate the environment, run:                $CONDA_CMD activate $ENV_NAME"
    echo -e "\t\t2. To install all dependencies, run:                bash $SCRIPT_NAME --install"
    echo -e "\t\t3. To deactivate the environment, run:              conda deactivate"
    echo -e "\n"
}

# ── Shared helpers for hardware installation ──────────────────────────────────

# Write sitecustomize.py that preloads conda's libstdc++ at Python startup.
# Required by C++ extensions compiled with GCC 14+ (ARX5, flexiv_rt) so they
# can find CXXABI_1.3.15 symbols without relying on the older system libstdc++.
write_sitecustomize() {
    local PY_VER
    PY_VER="$(python -c 'import sys; print(f"python{sys.version_info.major}.{sys.version_info.minor}")')"
    local SITE_DIR="${CONDA_PREFIX}/lib/${PY_VER}/site-packages"
    local TARGET="${SITE_DIR}/sitecustomize.py"

    if [[ -f "$TARGET" ]] && grep -q "RTLD_GLOBAL" "$TARGET" 2>/dev/null; then
        echo "[sitecustomize] Already configured."
        return
    fi
    echo "[sitecustomize] Writing libstdc++ preloader → $TARGET"
    cat > "$TARGET" << 'PYEOF'
"""
Preload conda's libstdc++ so C++ extensions compiled with GCC 14+ can find
CXXABI_1.3.15 symbols without relying on the system's older libstdc++.
Auto-generated by setup_env.sh.
"""
import ctypes
import os

prefix = os.environ.get("CONDA_PREFIX")
if prefix:
    p = os.path.join(prefix, "lib", "libstdc++.so.6")
    if os.path.exists(p):
        try:
            ctypes.CDLL(p, mode=ctypes.RTLD_GLOBAL)
        except Exception:
            pass
PYEOF
}

# conda installs a udev/ directory that confuses ctypes.util.find_library("udev"),
# causing pyudev/xensesdk to crash with "OSError: .../lib/udev: Is a directory".
fix_udev_discovery() {
    if [[ -d "${CONDA_PREFIX}/lib/udev" ]]; then
        echo "[udev] Renaming ${CONDA_PREFIX}/lib/udev to avoid pyudev clash..."
        local target="${CONDA_PREFIX}/lib/udev.rules.d"
        [[ -e "$target" ]] && target="${target}.bak.$(date +%s)"
        mv "${CONDA_PREFIX}/lib/udev" "$target" || true
    fi
    if [[ -e "${CONDA_PREFIX}/lib/libudev.so.1" && ! -e "${CONDA_PREFIX}/lib/libudev.so" ]]; then
        ln -s libudev.so.1 "${CONDA_PREFIX}/lib/libudev.so" || true
    fi
}

# TorchCodec follows an explicit compatibility matrix with PyTorch rather than
# a generic semver rule. Keep the expected version here so setup_env.sh can
# validate the installed wheel against the active torch release.
expected_torchcodec_version() {
    case "$1" in
        2.10) echo "0.10.0" ;;
        2.9) echo "0.9.1" ;;
        2.8) echo "0.7.0" ;;
        2.7) echo "0.5" ;;
        2.6) echo "0.2.1" ;;
        2.5) echo "0.1.1" ;;
        2.4) echo "0.0.3" ;;
        *) echo "" ;;
    esac
}

get_torch_major_minor() {
    python - <<'PY'
import re

try:
    import torch
except Exception:
    print("")
    raise SystemExit(0)

match = re.match(r"^(\d+)\.(\d+)", torch.__version__)
print(".".join(match.groups()) if match else "")
PY
}

version_matches_expected_release() {
    python - "$1" "$2" <<'PY'
import sys

from packaging.version import Version

actual, expected = sys.argv[1], sys.argv[2]

try:
    actual_release = Version(actual.split("+", 1)[0]).release
    expected_release = Version(expected).release
except Exception:
    print("no")
    raise SystemExit(0)

print("yes" if actual_release == expected_release else "no")
PY
}

ensure_python_package_min_version() {
    local package_name=$1
    local min_version=$2

    local current_version
    current_version="$(python - "$package_name" <<'PY'
import sys
from importlib.metadata import PackageNotFoundError, version

package_name = sys.argv[1]

try:
    print(version(package_name))
except PackageNotFoundError:
    print("")
PY
)"

    if [[ -z "$current_version" ]]; then
        echo "[python] Installing missing package: $package_name>=$min_version"
        uv pip install --upgrade "$package_name>=$min_version"
        return
    fi

    local is_compatible
    is_compatible="$(python - "$current_version" "$min_version" <<'PY'
import sys

from packaging.version import Version

current_version, min_version = sys.argv[1], sys.argv[2]
print("yes" if Version(current_version) >= Version(min_version) else "no")
PY
)"

    if [[ "$is_compatible" == "yes" ]]; then
        echo "[python] Keeping $package_name==$current_version"
    else
        echo "[python] Upgrading $package_name from $current_version to >=$min_version"
        uv pip install --upgrade "$package_name>=$min_version"
    fi
}

# ── Hardware module: ARX5 ─────────────────────────────────────────────────────

install_arx5() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " ARX5 SDK  →  pyarx"
    echo "══════════════════════════════════════════"

    local SDK_DIR="$PROJECT_ROOT/third_party/ARX5_SDK"
    if [[ ! -d "$SDK_DIR" ]]; then
        echo "ERROR: $SDK_DIR not found."
        echo "  Run: git submodule update --init third_party/ARX5_SDK"
        return 1
    fi

    # The PyPI spdlog package installs conflicting C++ headers — remove it first.
    uv pip uninstall spdlog 2>/dev/null || true

    bash "$SDK_DIR/build_python.sh"

    write_sitecustomize
    echo "[arx5] Done. Verify with: python -c 'import pyarx; print(pyarx)'"
}

# ── Hardware module: Flexiv ───────────────────────────────────────────────────

install_flexiv() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " libpyflexiv  →  flexiv_rt"
    echo "══════════════════════════════════════════"

    local LIB_DIR="$PROJECT_ROOT/third_party/libpyflexiv"
    local RDK_INSTALL="${RDK_INSTALL_PATH:-$HOME/rdk_install}"

    if [[ ! -d "$LIB_DIR" ]]; then
        echo "ERROR: $LIB_DIR not found."
        echo "  Run: git submodule update --init third_party/libpyflexiv"
        return 1
    fi

    # Stage 1: build ~/rdk_install (only if not already present)
    if [[ ! -f "$RDK_INSTALL/include/flexiv/rdk/robot.hpp" ]]; then
        echo ""
        echo "[flexiv] ~/rdk_install not found or incomplete. Build it first:"
        echo ""
        echo "  cd third_party/libpyflexiv"
        echo "  git submodule update --init flexiv_rdk"
        echo "  cd flexiv_rdk/thirdparty"
        echo "  bash build_and_install_dependencies.sh ~/rdk_install \$(nproc)"
        echo "  cd ../.. && mkdir -p build && cd build"
        echo "  cmake .. -DCMAKE_INSTALL_PREFIX=~/rdk_install -DCMAKE_PREFIX_PATH=~/rdk_install"
        echo "  cmake --build . --target install --config Release -j\$(nproc)"
        echo ""
        echo "Then rerun: bash setup_env.sh --install"
        return 1
    fi

    # Stage 2: build Python bindings (inside conda env)
    # IMPORTANT: only pass ~/rdk_install as CMAKE_PREFIX_PATH.
    # Do NOT include $CONDA_PREFIX — conda contains a different spdlog version
    # that will cause header conflicts (see third_party/libpyflexiv/README.md).
    local BUILD_DIR="$LIB_DIR/build"
    rm -rf "$BUILD_DIR"
    mkdir -p "$BUILD_DIR"

    cmake \
        -S "$LIB_DIR" \
        -B "$BUILD_DIR" \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_PREFIX_PATH="$RDK_INSTALL" \
        -DPython3_EXECUTABLE="$(which python)"

    cmake --build "$BUILD_DIR" -j"$(nproc)"

    uv pip install -e "$LIB_DIR" --no-build-isolation

    write_sitecustomize
    echo "[flexiv] RT SDK done. Verify with: python -c 'import flexiv_rt; print(flexiv_rt)'"

    # Install Flexiv NRT Python SDK from PyPI
    echo ""
    echo "[flexiv] Installing NRT SDK (flexivrdk)..."
    uv pip install "flexivrdk==1.8.0"
    echo "[flexiv] NRT SDK done. Verify with: python -c 'import flexivrdk; print(flexivrdk)'"
}

# ── Hardware module: Pico4 ────────────────────────────────────────────────────

install_pico4() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " XenseVR-PC-Service  →  xensevr_pc_service_sdk"
    echo "══════════════════════════════════════════"

    local SDK_SRC="$PROJECT_ROOT/third_party/XenseVR-PC-Service"
    local PYBIND_DIR="$PROJECT_ROOT/src/lerobot/teleoperators/pico4/xensevr-pc-service-pybind"

    if [[ ! -d "$SDK_SRC" ]]; then
        echo "ERROR: $SDK_SRC not found."
        echo "  Run: git submodule update --init third_party/XenseVR-PC-Service"
        return 1
    fi

    # Build the C SDK
    bash "$SDK_SRC/RoboticsService/PXREARobotSDK/build.sh"

    # Copy headers and .so into the pybind directory
    local CSDK_DIR="$SDK_SRC/RoboticsService/PXREARobotSDK"
    mkdir -p "$PYBIND_DIR/include" "$PYBIND_DIR/lib"
    cp "$CSDK_DIR/PXREARobotSDK.h" "$PYBIND_DIR/include/"
    cp -r "$CSDK_DIR/nlohmann" "$PYBIND_DIR/include/"
    cp "$CSDK_DIR/build/libPXREARobotSDK.so" "$PYBIND_DIR/lib/"

    # Build and install the Python bindings
    pushd "$PYBIND_DIR" > /dev/null
    rm -rf build *.egg-info
    uv pip uninstall xensevr_pc_service_sdk 2>/dev/null || true
    uv pip install . --no-build-isolation
    popd > /dev/null

    echo "[pico4] Done. Verify with: python -c 'import xensevr_pc_service_sdk; print(xensevr_pc_service_sdk)'"
}

# ── Hardware module: Xense ────────────────────────────────────────────────────

install_xense() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " xensesdk (vendored wheel) + XGripper"
    echo "══════════════════════════════════════════"

    local WHEEL="$PROJECT_ROOT/dist/xensesdk-2.0.0-cp312-cp312-linux_x86_64.whl"
    local GRIPPER_DIR="$PROJECT_ROOT/third_party/XGripper"

    if [[ ! -f "$WHEEL" ]]; then
        echo "ERROR: vendored xensesdk wheel not found: $WHEEL"
        return 1
    fi
    if [[ ! -d "$GRIPPER_DIR" ]]; then
        echo "ERROR: $GRIPPER_DIR not found."
        echo "  Run: git submodule update --init third_party/XGripper"
        return 1
    fi

    fix_udev_discovery

    # XGripper bundles libsurvive which links against libhidapi-libusb.
    # The conda cross-compiler uses its own sysroot and cannot find system hidapi,
    # so hidapi must be present in the conda environment before building.
    if ! compgen -G "${CONDA_PREFIX}/lib/libhidapi*.so*" > /dev/null 2>&1; then
        echo "[xense] hidapi not found in conda env — installing via conda-forge..."
        ${CONDA_CMD:-mamba} install -c conda-forge hidapi -y
    fi

    # Install xensesdk runtime deps explicitly because the wheel is installed
    # with --no-deps below (keeps the shared ARX5/Robostack env's numpy/opencv/
    # cryptography pins from being disturbed by the wheel's own constraints).
    # The rebuilt 2.0.0 wheel added cypack/ormsgpack/cyclonedds-nightly as
    # mandatory runtime deps — cypack is the FIRST import in xensesdk/__init__.py
    # and ormsgpack/cyclonedds are needed by the ezros layer — so they must be
    # listed here or `import xensesdk` fails with ModuleNotFoundError.
    uv pip install \
        "numpy>=1.26.4,<2.3.0" \
        "opencv-python>=4.10" \
        "pillow>=12.0" \
        "cryptography>=46.0" \
        "PyYAML>=6.0" \
        "h5py>=3.10" \
        "scipy>=1.14" \
        "lz4>=4.0" \
        "psutil>=7.0" \
        "spdlog>=2.0" \
        "cypack>=0.1.2" \
        "ormsgpack>=1.11.0" \
        "cyclonedds-nightly==2025.7.29" \
        "pyudev; platform_system=='Linux'"
    # Install xensesdk 2.0 from the vendored wheel under dist/. It bundles the
    # patched libxense_c.so flash reader (concurrent-connect EBADF fix), so no
    # separate xense_xu / pyxensexu build is needed. --no-deps keeps numpy 1.26.x.
    uv pip install --no-deps --force-reinstall "$WHEEL"
    # Install XGripper from local submodule (package name: xensegripper). It is
    # used by the serial / xense grippers and imports the xensesdk installed
    # above; --no-deps avoids PyPI wheels that are incomplete for Python 3.12.
    uv pip install -e "$GRIPPER_DIR" --no-deps
    # xensesdk requires a specific av version
    uv pip install av==15.1.0

    local PY_VER
    PY_VER="$(python -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"

    # onnxruntime-gpu uses dlopen() and ignores LD_LIBRARY_PATH — patch its RPATH.
    local ONNX_SO="${CONDA_PREFIX}/lib/python${PY_VER}/site-packages/onnxruntime/capi/libonnxruntime_providers_cuda.so"
    if [[ -f "$ONNX_SO" ]]; then
        echo "[xense] Fixing onnxruntime-gpu RPATH..."
        uv pip install patchelf
        patchelf --set-rpath "${CONDA_PREFIX}/lib" "$ONNX_SO"
        echo "[xense] RPATH set: $(patchelf --print-rpath "$ONNX_SO")"
    fi

    # OpenCV's bundled Qt plugin causes XCB errors inside conda envs.
    local QXCB="${CONDA_PREFIX}/lib/python${PY_VER}/site-packages/cv2/qt/plugins/platforms/libqxcb.so"
    if [[ -f "$QXCB" ]]; then
        echo "[xense] Removing OpenCV bundled Qt plugin: $QXCB"
        rm -f "$QXCB"
    fi

    if python - <<'PY'
from xensesdk.flash.linux_backend import LinuxFlashBackend
raise SystemExit(0 if LinuxFlashBackend().available else 1)
PY
    then
        echo "[xense] xensesdk flash backend (libxense_c) is available."
    else
        echo "[xense] ERROR: xensesdk flash backend verification failed."
        return 1
    fi

    echo "[xense] Done. Verify with: python -c 'import xensesdk; print(xensesdk)'"
}

# ── Hardware module: Elite CS (bi_elite_cs66_rt / elite_cs66_rt) ─────────────

install_elite() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " Elite CS SDK (C++ + Python)  →  elite_cs_sdk"
    echo "══════════════════════════════════════════"

    local CPP_DIR="$PROJECT_ROOT/third_party/elite-robots-cs-sdk"
    local PY_DIR="$PROJECT_ROOT/third_party/elite-robots-cs-sdk-python"

    if [[ ! -f "$CPP_DIR/CMakeLists.txt" ]]; then
        echo "ERROR: $CPP_DIR not found."
        echo "  Run: git submodule update --init third_party/elite-robots-cs-sdk"
        return 1
    fi
    if [[ ! -f "$PY_DIR/CMakeLists.txt" ]]; then
        echo "ERROR: $PY_DIR not found."
        echo "  Run: git submodule update --init third_party/elite-robots-cs-sdk-python"
        return 1
    fi

    # C++ build prerequisites (system packages, see Elite BuildGuide):
    #   sudo apt install -y build-essential cmake libboost-all-dev libssh-dev \
    #                        libeigen3-dev liborocos-kdl-dev
    # Python build deps — the python_wheel target builds with --no-build-isolation.
    uv pip install --upgrade pybind11 pybind11-stubgen build setuptools wheel

    # Build the pybind wheel, pointing the Python SDK at our LOCAL C++ SDK
    # submodule (ELITE_CS_SDK_REPO is required and must be a local path — the
    # Python build add_subdirectory()s it instead of fetching over the network).
    local BUILD_DIR="$PY_DIR/build"
    rm -rf "$BUILD_DIR"
    cmake -S "$PY_DIR" -B "$BUILD_DIR" \
        -DCMAKE_BUILD_TYPE=Release \
        -DELITE_CS_SDK_REPO="$CPP_DIR" \
        -DELITE_COMPILE_KIN_PLUGIN=ON \
        -DPython3_EXECUTABLE="$(which python)"
    cmake --build "$BUILD_DIR" --target python_wheel -j"$(nproc)"

    local WHEEL
    WHEEL="$(ls -t "$PY_DIR"/dist/elite_cs_sdk-*.whl 2>/dev/null | head -1)"
    if [[ -z "$WHEEL" ]]; then
        echo "[elite] ERROR: build did not produce a wheel under $PY_DIR/dist/"
        return 1
    fi
    uv pip install --force-reinstall "$WHEEL"

    echo "[elite] Done. Verify with: python -c 'import elite_cs_sdk; print(elite_cs_sdk.__file__)'"
}

# ── Hardware module: Franka Research 3 ───────────────────────────────────────

install_franka() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " Franka Research 3 (pylibfranka)  →  websockets"
    echo "══════════════════════════════════════════"

    local SDK_DIR="$PROJECT_ROOT/third_party/xense_franka"

    if [[ ! -d "$SDK_DIR" ]]; then
        echo "ERROR: $SDK_DIR not found."
        echo "  Run: git submodule update --init third_party/xensesdk"
        return 1
    fi

    uv pip install \
        "websockets>=12.0" \
        "pylibfranka==0.20.3"

    uv pip install -e "$SDK_DIR"

    uv pip install "websockets>=12.0"
    echo "[franka] Done. Verify with: python -c 'import websockets; print(websockets.__version__)'"
}

# ── Hardware module: SpaceMouse ───────────────────────────────────────────────

install_spacemouse() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " SpaceMouse — pyspacemouse"
    echo "══════════════════════════════════════════"

    if ! compgen -G "${CONDA_PREFIX}/lib/libhidapi*.so*" > /dev/null; then
        echo "[spacemouse] WARN: hidapi shared library not found under ${CONDA_PREFIX}/lib"
        echo "[spacemouse] Re-run the conda environment update to install the conda-forge hidapi package."
        return 1
    fi

    uv pip install pyspacemouse
    echo "[spacemouse] No system-level udev or group changes were applied."
    echo "[spacemouse] If hidraw permissions are restricted on the host OS, configure them manually outside setup_env.sh."

    echo "[spacemouse] Done."
}

# ── Hardware module: Dynamixel (TRLC leader, SO arms, etc.) ─────────────────

install_dynamixel() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " Dynamixel — dynamixel-sdk (Python)"
    echo "══════════════════════════════════════════"

    # Keep in sync with pyproject.toml: dynamixel = ["dynamixel-sdk>=3.7.31,<3.9.0"]
    if ! uv pip install "dynamixel-sdk>=3.7.31,<3.9.0"; then
        echo "[dynamixel] ERROR: pip install dynamixel-sdk failed"
        return 1
    fi
    echo "[dynamixel] Done. Verify with: python -c 'import dynamixel_sdk; print(dynamixel_sdk.__file__)'"
}

# ── Argument parsing ──────────────────────────────────────────────────────────

# Check if an environment name is provided
if [[ -n "$2" ]]; then
    ENV_NAME="$2"
else
    ENV_NAME="lerobot-xense"
fi

# Check if the --conda parameter is passed
if [[ "$1" == "--conda" ]]; then
    # Initialize conda
    if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniconda3/etc/profile.d/conda.sh"
    elif [ -f "$HOME/anaconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/anaconda3/etc/profile.d/conda.sh"
    else
        echo "Conda initialization script not found. Please install Miniconda3 or Anaconda3 or Miniforge3."
        exit 1
    fi
    create_environment "conda" "$ENV_NAME" || exit 1

# Check if the --mamba parameter is passed
elif [[ "$1" == "--mamba" ]]; then
    # Initialize mamba (miniforge)
    if [ -f "$HOME/miniforge3/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniforge3/etc/profile.d/conda.sh"
    elif [ -f "$HOME/mambaforge/etc/profile.d/conda.sh" ]; then
        . "$HOME/mambaforge/etc/profile.d/conda.sh"
    else
        echo "Mamba initialization script not found. Please install Miniforge3 or Mambaforge."
        exit 1
    fi
    # Also source mamba.sh if available for full mamba support
    if [ -f "$HOME/miniforge3/etc/profile.d/mamba.sh" ]; then
        . "$HOME/miniforge3/etc/profile.d/mamba.sh"
    elif [ -f "$HOME/mambaforge/etc/profile.d/mamba.sh" ]; then
        . "$HOME/mambaforge/etc/profile.d/mamba.sh"
    fi
    create_environment "mamba" "$ENV_NAME" || exit 1

# Check if the --install parameter is passed
elif [[ "$1" == "--install" ]]; then
    # Get the currently activated conda environment name
    if [[ -z "${CONDA_DEFAULT_ENV}" ]]; then
        echo "Error: No conda/mamba environment is currently activated."
        echo "Please activate an environment first with: conda/mamba activate <env_name>"
        exit 1
    fi
    ENV_NAME=${CONDA_DEFAULT_ENV}

    # Detect conda/mamba command
    if [ -f "$HOME/miniforge3/etc/profile.d/conda.sh" ]; then
        CONDA_CMD="mamba"
    else
        CONDA_CMD="conda"
    fi

    echo "[INFO] Updating conda environment '$ENV_NAME' from: $CONDA_ENV_FILE"
    if ! $CONDA_CMD env update -f "$CONDA_ENV_FILE" -n "$ENV_NAME"; then
        echo "[ERROR] Failed to update conda environment '$ENV_NAME' from: $CONDA_ENV_FILE"
        exit 1
    fi

    echo -e "\n[INFO] Conda dependencies installed/updated for '$ENV_NAME'.\n"
    uv pip install --upgrade pip
    # Ensure editable installs (PEP 660) work without downgrading newer compatible packages.
    ensure_python_package_min_version setuptools 71.0.0
    ensure_python_package_min_version wheel 0.40.0

    # Workaround for Python ctypes.util.find_library("udev") on conda envs:
    # Hacking the udev library discovery to avoid issues with pyudev/xensesdk.
    # If $CONDA_PREFIX/lib/udev exists as a directory, Python may return that directory as the "udev" library,
    # causing pyudev/xensesdk to crash with: "OSError: .../lib/udev: Is a directory".
    fix_udev_discovery

    # evdev (pulled in by pynput) generates ecodes.c from /usr/include/linux/ at
    # build time, then compiles it with the conda cross-compiler which uses its
    # own sysroot. Ubuntu's linux-libc-dev now ships KEY_LINK_PHONE (added in
    # Linux 6.14), so evdev references it in ecodes.c, but the conda sysroot's
    # older kernel headers lack it.  Patch the sysroot header in place so the
    # conda compiler can find the constant without mixing incompatible glibc headers.
    _SYSROOT_CODES="${CONDA_PREFIX}/x86_64-conda-linux-gnu/sysroot/usr/include/linux/input-event-codes.h"
    if [[ -f "$_SYSROOT_CODES" ]] && ! grep -q "KEY_LINK_PHONE" "$_SYSROOT_CODES"; then
        echo "[INFO] Patching conda sysroot: adding KEY_LINK_PHONE to input-event-codes.h"
        printf '\n#ifndef KEY_LINK_PHONE\n#define KEY_LINK_PHONE 0x1bf  /* AL Phone Syncing, Linux 6.14 */\n#endif\n' >> "$_SYSROOT_CODES"
    fi

    echo "[INFO] Installing Lerobot from pyproject.toml"
    if uv pip install -e .; then
        echo "[INFO] Lerobot installed successfully!"
    else
        echo "[ERROR] Lerobot installation failed. See the error output above."
        exit 1
    fi

    # Verify critical package versions
    echo "[INFO] Verifying package versions..."
    TORCHCODEC_VER=$(python -c "import torchcodec; print(torchcodec.__version__)" 2>/dev/null || echo "NOT INSTALLED")
    AV_VER=$(python -c "import av; print(av.__version__)" 2>/dev/null || echo "NOT INSTALLED")
    TORCH_VER=$(python -c "import torch; print(torch.__version__)" 2>/dev/null || echo "NOT INSTALLED")
    TORCH_MAJOR_MINOR=$(get_torch_major_minor)
    EXPECTED_TORCHCODEC_VER=$(expected_torchcodec_version "$TORCH_MAJOR_MINOR")
    echo "  - torch: $TORCH_VER"
    if [[ -n "$EXPECTED_TORCHCODEC_VER" ]]; then
        echo "  - torchcodec: $TORCHCODEC_VER (should be $EXPECTED_TORCHCODEC_VER for torch $TORCH_MAJOR_MINOR)"
    else
        echo "  - torchcodec: $TORCHCODEC_VER (no compatibility override defined for torch $TORCH_VER)"
    fi
    echo "  - av (pyav): $AV_VER (should be 15.1.0)"

    if [[ -n "$EXPECTED_TORCHCODEC_VER" ]]; then
        if [[ "$(version_matches_expected_release "$TORCHCODEC_VER" "$EXPECTED_TORCHCODEC_VER")" != "yes" ]]; then
            echo "[WARN] torchcodec version mismatch! Expected $EXPECTED_TORCHCODEC_VER for torch $TORCH_MAJOR_MINOR, got $TORCHCODEC_VER"
            uv pip install "torchcodec==$EXPECTED_TORCHCODEC_VER" --force-reinstall
        fi
    else
        echo "[WARN] Skipping torchcodec pin verification for unsupported torch version: $TORCH_VER"
    fi

    if [[ "$AV_VER" != "15.1.0" ]]; then
        echo "[WARN] av (pyav) version mismatch! Expected 15.1.0, got $AV_VER"
        uv pip install av==15.1.0 --force-reinstall
    fi

    echo ""
    echo "[INFO] Installing hardware SDK bindings..."
    echo ""

    install_arx5      || echo "[WARN] arx5 installation skipped or failed (see above)"
    install_flexiv    || echo "[WARN] flexiv installation skipped or failed (see above)"
    install_franka    || echo "[WARN] franka installation skipped or failed (see above)"
    ( install_pico4 ) || echo "[WARN] pico4 installation skipped or failed (see above)"
    install_xense     || echo "[WARN] xense installation skipped or failed (see above)"
    install_elite     || echo "[WARN] elite installation skipped or failed (see above)"
    install_spacemouse || echo "[WARN] spacemouse installation skipped or failed (see above)"
    install_dynamixel  || echo "[WARN] dynamixel-sdk installation skipped or failed (see above)"


    # ── Post-install verification ────────────────────────────────────────────
    echo ""
    echo "══════════════════════════════════════════"
    echo " Post-install verification"
    echo "══════════════════════════════════════════"
    _VERIFY_FAIL=0
    while IFS='|' read -r _pkg _import; do
        _out="$(python -c "$_import" 2>&1)" && \
            echo "[OK]    $_pkg: $_out" || \
            { echo "[ERROR] $_pkg: $_out"; _VERIFY_FAIL=1; }
    done <<'VERIFY'
lerobot|import importlib.metadata as M, lerobot; print("v"+M.version("lerobot"), "->", lerobot.__file__)
pyarx|import importlib.metadata as M, pyarx; print("v"+M.version("pyarx"), "->", pyarx.__file__)
flexiv_rt|import importlib.metadata as M, flexiv_rt; print("v"+M.version("flexiv_rt"), "->", flexiv_rt.__file__)
xensevr_pc_service_sdk|import importlib.metadata as M, xensevr_pc_service_sdk; print("v"+M.version("xensevr_pc_service_sdk"), "->", xensevr_pc_service_sdk.__file__)
xensesdk|import importlib.metadata as M, xensesdk; print("v"+M.version("xensesdk"), "->", xensesdk.__file__)
xensegripper|import importlib.metadata as M, xensegripper; print("v"+M.version("xgripper"), "->", xensegripper.__file__)
xensesdk flash|from xensesdk.flash.linux_backend import LinuxFlashBackend; print("available" if LinuxFlashBackend().available else "NOT available")
elite_cs_sdk|import importlib.metadata as M, elite_cs_sdk; print("v"+M.version("elite_cs_sdk"), "->", elite_cs_sdk.__file__)
dynamixel_sdk|import importlib.metadata as M, dynamixel_sdk; print("v"+M.version("dynamixel_sdk"), "->", dynamixel_sdk.__file__)
VERIFY

    echo ""
    if [[ $_VERIFY_FAIL -eq 0 ]]; then
        echo "[INFO] All packages verified successfully."
    else
        echo "[ERROR] Some packages failed verification. Review the [ERROR] lines above."
    fi

    echo ""
    echo "[INFO] Lerobot-Xense installation complete."
    exit $_VERIFY_FAIL
else
    echo "Invalid argument. Usage:"
    echo "  --conda [env_name]   Create a conda environment (requires Miniconda/Anaconda)"
    echo "  --mamba [env_name]   Create a mamba environment (requires Miniforge)"
    echo "  --install            Install base package + all hardware SDK bindings"
    exit 1
fi
