# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot are generated by teleoperation.

Example (SO-100):

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30}}" \
    --robot.id=black \
    --dataset.repo_id=<my_username>/<my_dataset_name> \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    --dataset.streaming_encoding=true \
    --dataset.encoder_threads=2 \
    --display_data=true
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
```

Example (Bimanual Flexiv Rizon4 RT + Bi-Pico4):

```shell
lerobot-record \
    --robot.type=bi_flexiv_rizon4_rt \
    --robot.left_config.robot_ip=192.168.2.100 \
    --robot.left_config.local_ip=192.168.2.1 \
    --robot.right_config.robot_ip=192.168.3.100 \
    --robot.right_config.local_ip=192.168.3.1 \
    --robot.id=bimanual \
    --teleop.type=bi_pico4 \
    --teleop.id=bimanual \
    --dataset.repo_id=<my_username>/<my_dataset_name> \
    --dataset.num_episodes=50 \
    --dataset.single_task="Pick up the cube" \
    --dataset.fps=30 \
    --dataset.episode_time_s=60 \
    --dataset.reset_time_s=30 \
    --dataset.streaming_encoding=true \
    --dataset.encoder_threads=2
```

Example (XenseFlare + SpaceMouse):

```shell
lerobot-record \
    --robot.type=xense_flare \
    --robot.id=right \
    --teleop.type=spacemouse \
    --teleop.id=right \
    --dataset.repo_id=<my_username>/<my_dataset_name> \
    --dataset.num_episodes=50 \
    --dataset.single_task="Pick up the cube" \
    --dataset.fps=30 \
    --display_data=true
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so_follower \
  --robot.left_arm_config.port=/dev/tty.usbmodem5A460822851 \
  --robot.right_arm_config.port=/dev/tty.usbmodem5A460814411 \
  --robot.id=bimanual_follower \
  --robot.left_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 3, "width": 640, "height": 480, "fps": 30},
  }' --robot.right_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30},
    front: {"type": "opencv", "index_or_path": 4, "width": 640, "height": 480, "fps": 30},
  }' \
  --teleop.type=bi_so_leader \
  --teleop.left_arm_config.port=/dev/tty.usbmodem5A460852721 \
  --teleop.right_arm_config.port=/dev/tty.usbmodem5A460819811 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm" \
  --dataset.streaming_encoding=true \
  --dataset.encoder_threads=2
```
"""

import threading
import time
from concurrent.futures import ThreadPoolExecutor
from dataclasses import asdict, dataclass, field
from pathlib import Path
from pprint import pformat

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.cameras.zmq.configuration_zmq import ZMQCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.utils import build_dataset_frame, combine_feature_dicts, hw_to_dataset_features
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    bi_elite_cs66_rt,
    bi_flexiv_rizon4_rt,
    elite_cs66_rt,
    flexiv_rizon4_rt,
    make_robot_from_config,
    xense_flare as xense_flare_robot,
    xense_multisensor,
)
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_pico4,
    make_teleoperator_from_config,
    mock_teleop,
    pico4,
    spacemouse,
    vive_tracker,
    xense_flare,
    trlc_leader,
)
from lerobot.utils.constants import ACTION, OBS_STR
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    refresh_listener_events,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.import_utils import register_third_party_plugins
from lerobot.utils.robot_utils import busy_wait, get_logger, precise_sleep
from lerobot.utils.utils import (
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import init_rerun, log_rerun_data

logger = get_logger("lerobot_record")


def _format_slow_frame_obs_suffix(robot: Robot | None) -> str:
    if robot is None:
        return ""

    timing = getattr(robot, "_last_obs_timing", None)
    if not isinstance(timing, dict):
        return ""

    parts: list[str] = []
    total_ms = timing.get("total_ms")
    if isinstance(total_ms, (int, float)):
        parts.append(f"obs={float(total_ms):.1f}ms")

    arm_items = [
        (key[:-3], float(value))
        for key, value in timing.items()
        if key.endswith("_arm_ms") and isinstance(value, (int, float))
    ]
    if arm_items:
        parts.append(f"arms={sum(value for _, value in arm_items):.1f}ms")

    grip_items = [
        (key[:-3], float(value))
        for key, value in timing.items()
        if key.endswith("_grip_ms") and isinstance(value, (int, float))
    ]
    if grip_items:
        parts.append(f"grips={sum(value for _, value in grip_items):.1f}ms")

    cameras_ms = timing.get("cameras_ms")
    if isinstance(cameras_ms, (int, float)):
        parts.append(f"cams={float(cameras_ms):.1f}ms")

    cam_items = [
        (key[4:-4], float(value))
        for key, value in timing.items()
        if (
            key.startswith("cam[")
            and key.endswith("]_ms")
            and isinstance(value, (int, float))
        )
    ]
    cam_items.sort(key=lambda item: item[1], reverse=True)

    obs_part_items = arm_items + grip_items + cam_items
    obs_part_items.sort(key=lambda item: item[1], reverse=True)
    if obs_part_items:
        visible_obs_items = [item for item in obs_part_items if item[1] >= 0.1]
        if not visible_obs_items:
            visible_obs_items = obs_part_items
        top_parts = ", ".join(
            f"{name}={value:.1f}ms" for name, value in visible_obs_items[:4]
        )
        parts.append(f"top_obs={top_parts}")

    return f" | {' '.join(parts)}" if parts else ""


def _record_loop_sleep(
    start_loop_t: float,
    fps: int,
    start_episode_t: float,
    robot: Robot | None = None,
) -> None:
    if fps <= 0:
        return

    budget_s = 1.0 / fps
    dt_s = time.perf_counter() - start_loop_t
    remaining_s = budget_s - dt_s
    if remaining_s > 0:
        busy_wait(remaining_s)
        return

    episode_t_s = time.perf_counter() - start_episode_t
    robot_name = (
        getattr(robot, "name", None) or getattr(type(robot), "__name__", "record")
        if robot is not None
        else "record"
    )
    logger.warn(
        f"[slow_frame] robot={robot_name} t={episode_t_s:.3f}s "
        f"loop={dt_s * 1e3:.1f}ms budget={budget_s * 1e3:.1f}ms "
        f"overrun={(-remaining_s) * 1e3:.1f}ms"
        f"{_format_slow_frame_obs_suffix(robot)}"
    )


RAW_PASSTHROUGH_RECORD_PAIRS = frozenset(
    {
        ("flexiv_rizon4_rt", "pico4"),
        ("bi_flexiv_rizon4_rt", "bi_pico4"),
        ("pylibfranka_research3", "pico4"),
        ("pylibfranka_research3", "btgamepad"),
    }
)


def extract_joint_positions(obs):
    """提取关节位置，排除摄像头数据"""
    joint_positions = {}
    for key, value in obs.items():
        if (
            key.endswith(".pos")
            and not key.startswith("head")
            and not key.startswith("left_wrist")
            and not key.startswith("right_wrist")
        ):
            joint_positions[key] = value
    return joint_positions


def apply_velocity_limits(
    current_action: dict, prev_action: dict, dt: float, robot=None
) -> dict:
    """Apply velocity limits to action to ensure consistency with inference-time clipping.

    This ensures that recorded actions are physically executable during policy inference.

    Args:
        current_action: Current action dictionary with joint positions
        prev_action: Previous action dictionary with joint positions
        dt: Time step between actions (typically 1/fps)
        robot: Robot instance to get velocity limits from robot_configs

    Returns:
        Velocity-limited action dictionary
    """
    if prev_action is None:
        return current_action

    # Get velocity limits from robot config to ensure consistency with C++ settings
    if robot is not None and hasattr(robot, "robot_configs"):
        # Read from robot config (same as C++ controller uses)
        left_config = robot.robot_configs["left_config"]
        joint_vel_limits = (
            left_config.joint_vel_max.tolist()
        )  # Convert numpy array to list
        gripper_vel_limit = left_config.gripper_vel_max
    else:
        # Fallback to hardcoded values if robot config not available
        # From config.h: [20.0, 20.0, 20.5, 20.5, 20.0, 20.0] rad/s, gripper: 0.3 m/s
        joint_vel_limits = [20.0, 20.0, 20.5, 20.5, 20.0, 20.0]  # rad/s
        gripper_vel_limit = 0.3  # m/s

    limited_action = current_action.copy()
    clip_count = 0

    # Apply joint velocity limits
    for i in range(6):
        left_key = f"left_joint_{i+1}.pos"
        right_key = f"right_joint_{i+1}.pos"

        for key in [left_key, right_key]:
            if key in current_action and key in prev_action:
                current_pos = current_action[key]
                prev_pos = prev_action[key]
                delta_pos = current_pos - prev_pos
                max_delta = joint_vel_limits[i] * dt

                if abs(delta_pos) > max_delta:
                    # Clip to maximum allowed change
                    sign = 1 if delta_pos > 0 else -1
                    limited_action[key] = prev_pos + sign * max_delta
                    clip_count += 1
                    logger.debug(
                        f"Clipped {key}: {delta_pos:.3f} -> {sign * max_delta:.3f} rad"
                    )

    # Apply gripper velocity limits
    for gripper_key in ["left_gripper.pos", "right_gripper.pos"]:
        if gripper_key in current_action and gripper_key in prev_action:
            current_pos = current_action[gripper_key]
            prev_pos = prev_action[gripper_key]
            delta_pos = current_pos - prev_pos
            max_delta = gripper_vel_limit * dt

            if abs(delta_pos) > max_delta:
                # Clip to maximum allowed change
                sign = 1 if delta_pos > 0 else -1
                limited_action[gripper_key] = prev_pos + sign * max_delta
                clip_count += 1
                logger.debug(
                    f"Clipped {gripper_key}: {delta_pos:.3f} -> {sign * max_delta:.3f} m"
                )

    if clip_count > 0:
        logger.debug(f"Applied velocity limits: {clip_count} joints clipped")

    return limited_action


def _start_reset_in_background(robot, teleop, set_done):
    """Run robot.reset_to_initial_position() in a daemon thread.

    Calls set_done() in the finally block so the caller can clear any
    resetting flag regardless of success or failure.
    """
    logger.info(
        "Starting reset_to_initial_position in background (A button pressed)..."
    )

    def _thread():
        try:
            robot.reset_to_initial_position()
            logger.info("✅ reset_to_initial_position completed")
            tcp = robot.get_current_tcp_pose_quat()
            teleop.reset_to_pose(tcp[:7], tcp[7])
        except Exception as e:
            logger.error(f"Error during reset_to_initial_position: {e}")
        finally:
            set_done()

    threading.Thread(target=_thread, daemon=True).start()


def _sync_rt_teleop_to_robot_pose(robot: Robot, teleop: Teleoperator | None) -> None:
    if teleop is None or not hasattr(teleop, "reset_to_pose"):
        return

    if teleop.name == "bi_pico4":
        left_pose, right_pose = robot.get_current_tcp_pose_quat()
        teleop.reset_to_pose(left_pose[:7], right_pose[:7], left_pose[7], right_pose[7])
    elif teleop.name in {"pico4", "btgamepad"}:
        pose = robot.get_current_tcp_pose_quat()
        teleop.reset_to_pose(pose[:7], pose[7])


def _sync_elite_teleop_to_robot_pose(robot: Robot, teleop: Teleoperator | None) -> None:
    """Re-seed teleop's internal target from Elite CS66's current TCP pose.

    Called after a non-blocking ``reset_to_initial_position()`` trajectory
    completes so the next ``send_action`` doesn't slam the controller with a
    stale (pre-reset) target. Dispatches by teleop type: SpaceMouse's internal
    accumulator is Euler, Pico4 uses quaternion.
    """
    if teleop is None or not hasattr(teleop, "reset_to_pose"):
        return
    if teleop.name == "spacemouse":
        pose_euler = robot.get_current_tcp_pose_euler()
        teleop.reset_to_pose(pose_euler[:6], pose_euler[6])
        if hasattr(teleop, "_start_pose_6d"):
            teleop._start_pose_6d = pose_euler[:6].copy()
        if hasattr(teleop, "_start_gripper_pos"):
            teleop._start_gripper_pos = float(pose_euler[6])
    elif teleop.name == "pico4":
        pose_quat = robot.get_current_tcp_pose_quat()
        teleop.reset_to_pose(pose_quat[:7], pose_quat[7])


def _use_raw_passthrough_record(robot_type: str, teleop_type: str | None) -> bool:
    return (robot_type, teleop_type) in RAW_PASSTHROUGH_RECORD_PAIRS


def _build_raw_passthrough_dataset_features(
    robot: Robot, use_videos: bool
) -> dict[str, dict]:
    return combine_feature_dicts(
        hw_to_dataset_features(robot.action_features, ACTION, use_videos),
        hw_to_dataset_features(robot.observation_features, OBS_STR, use_videos),
    )


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path'). If None, defaults to $HF_LEROBOT_HOME/repo_id.
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    # Video codec for encoding videos. Options: 'h264', 'hevc', 'libsvtav1', 'auto',
    # or hardware-specific: 'h264_videotoolbox', 'h264_nvenc', 'h264_vaapi', 'h264_qsv'.
    # Use 'auto' to auto-detect the best available hardware encoder.
    vcodec: str = "libsvtav1"
    # Enable streaming video encoding: encode frames in real-time during capture instead
    # of writing PNG images first. Makes save_episode() near-instant. More info in the documentation: https://huggingface.co/docs/lerobot/streaming_video_encoding
    streaming_encoding: bool = False
    # Maximum number of frames to buffer per camera when using streaming encoding.
    # ~1s buffer at 30fps. Provides backpressure if the encoder can't keep up.
    encoder_queue_maxsize: int = 30
    # Number of threads per encoder instance. None = auto (codec default).
    # Lower values reduce CPU usage, maps to 'lp' (via svtav1-params) for libsvtav1 and 'threads' for h264/hevc..
    encoder_threads: int | None = None
    # Rename map for the observation to override the image and state keys
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Teleoperator used to control the robot
    teleop: TeleoperatorConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Display data on a remote Rerun server
    display_ip: str | None = None
    # Port of the remote Rerun server
    display_port: int | None = None
    # Whether to  display compressed images in Rerun
    display_compressed_images: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False

    def __post_init__(self):
        # Robots that act as both observation source and action source
        # (i.e. "self-driven" data-collection devices like handheld grippers)
        # do not require a separate teleoperator. ``xense_flare`` was the
        # first; ``taccap_gripper`` follows the same pattern.
        if self.teleop is None and self.robot.type not in ("xense_flare", "taccap_gripper"):
            raise ValueError("A teleoperator configuration is required to control the robot.")


""" --------------- record_loop() data flow --------------------------
       [ Robot ]
           V
     [ robot.get_observation() ] ---> obs
           V
     [ teleop.get_action() ] ---> raw_action
           V
     [ robot.send_action() ] -- (Robot Executes)
           V
     ( Save to Dataset )
           V
     ( Rerun Log / Loop Wait )
"""


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
    display_compressed_images: bool = False,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    no_action_count = 0
    timestamp = 0
    start_episode_t = time.perf_counter()
    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()

        if events["exit_early"]:
            events["exit_early"] = False
            break

        # Get robot observation
        obs = robot.get_observation()

        if dataset is not None:
            observation_frame = build_dataset_frame(dataset.features, obs, prefix=OBS_STR)

        # Get action from teleop
        if isinstance(teleop, Teleoperator):
            raw_action = teleop.get_action()
            action_values = raw_action
            robot_action_to_send = raw_action
        else:
            no_action_count += 1
            if no_action_count == 1 or no_action_count % 10 == 0:
                logger.warning(
                    "No teleoperator provided, skipping action generation. "
                    "This is likely to happen when resetting the environment without a teleop device. "
                    "The robot won't be at its rest position at the start of the next episode."
                )
            continue

        # Send action to robot
        _sent_action = robot.send_action(robot_action_to_send)

        # Write to dataset
        if dataset is not None:
            action_frame = build_dataset_frame(dataset.features, action_values, prefix=ACTION)
            frame = {**observation_frame, **action_frame, "task": single_task}
            dataset.add_frame(frame)

        if display_data:
            log_rerun_data(
                observation=obs, action=action_values, compress_images=display_compressed_images
            )

        dt_s = time.perf_counter() - start_loop_t

        sleep_time_s: float = 1 / fps - dt_s
        if sleep_time_s < 0:
            logger.warning(
                f"Record loop is running slower ({1 / dt_s:.1f} Hz) than the target FPS ({fps} Hz). Dataset frames might be dropped and robot control might be unstable. Common causes are: 1) Camera FPS not keeping up 2) CPU starvation"
            )

        precise_sleep(max(sleep_time_s, 0.0))

        timestamp = time.perf_counter() - start_episode_t


@safe_stop_image_writer
def xense_flare_record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    dataset: LeRobotDataset | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
):
    """
    Record loop for XenseFlare data collection gripper.

    XenseFlare is special because it acts as both:
    - A robot (provides observation: camera, tactile, gripper position)
    - A teleoperator (provides action: Vive Tracker pose + gripper position)

    The action comes from robot.get_action() instead of a separate teleoperator.
    """
    if dataset is not None and dataset.fps != fps:
        raise ValueError(
            f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps})."
        )

    timestamp = 0
    start_episode_t = time.perf_counter()

    # Variables for action shifting (only used in manual demonstration mode)
    prev_observation = None
    prev_observation_frame = None

    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()
        refresh_listener_events(events)

        if events["exit_early"]:
            events["exit_early"] = False
            break

        if events["rerecord_episode"]:
            logger.info("Re-record episode requested, exiting record loop early")
            break

        # Get robot observation (camera, tactile, gripper position)
        current_observation = robot.get_observation()
        current_observation_frame = None

        if dataset is not None:
            current_observation_frame = build_dataset_frame(
                dataset.features, current_observation, prefix=OBS_STR
            )

        current_action = robot.get_action()

        if prev_observation is not None and dataset is not None:
            # Manual demonstration mode with action shifting
            # Use current frame's action as previous frame's action
            current_action_frame = build_dataset_frame(
                dataset.features, current_action, prefix=ACTION
            )

            frame = {
                **prev_observation_frame,
                **current_action_frame,
                "task": single_task,
            }
            dataset.add_frame(frame)

        if display_data:
            log_rerun_data(observation=current_observation, action=current_action)

        # Update for next iteration
        prev_observation = current_observation
        prev_observation_frame = current_observation_frame

        _record_loop_sleep(
            start_loop_t=start_loop_t,
            fps=fps,
            start_episode_t=start_episode_t,
            robot=robot,
        )

        timestamp = time.perf_counter() - start_episode_t


@safe_stop_image_writer
def flexiv_rizon4_rt_record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(
            f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps})."
        )

    if isinstance(teleop, list):
        raise ValueError("Multi-teleop mode is not supported in this version.")

    timestamp = 0
    start_episode_t = time.perf_counter()
    prev_rt_moving = False
    prev_observation_frame = None  # for shifted-frame logic during RT reset

    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()
        reset_triggered = False
        refresh_listener_events(events)

        if events["stop_recording"]:
            logger.info("Stop recording requested, exiting record loop early")
            break

        if events["rerecord_episode"]:
            logger.info("Re-record episode requested, exiting record loop early")
            break

        if events["exit_early"]:
            events["exit_early"] = False
            logger.info("Exit early requested, exiting record loop early")
            break

        if events["go_start"]:
            events["go_start"] = False
            if hasattr(robot, "reset_to_initial_position"):
                try:
                    logger.info(
                        "Reset to initial position (keyboard or controller button)"
                    )
                    robot.reset_to_initial_position()
                    reset_triggered = True
                except Exception as e:
                    logger.error(f"Error during reset_to_initial_position: {e}")

        current_observation = robot.get_observation()
        current_observation_frame = None

        if dataset is not None:
            current_observation_frame = build_dataset_frame(
                dataset.features, current_observation, prefix=OBS_STR
            )

        robot_is_moving = hasattr(robot, "rt_moving") and robot.rt_moving
        if robot_is_moving:
            prev_rt_moving = True

        if prev_rt_moving:
            if not robot_is_moving:
                prev_rt_moving = False
                try:
                    _sync_rt_teleop_to_robot_pose(robot, teleop)
                    logger.info("Synced teleop to robot pose after RT reset")
                except Exception as e:
                    logger.error(f"Failed to sync teleop after RT reset: {e}")

        if isinstance(teleop, Teleoperator):
            teleop_action = teleop.get_action()

            if reset_triggered:
                sent_action = teleop_action  # not sent, used only for display
            elif robot_is_moving:
                sent_action = teleop_action  # not sent, used only for display
            else:
                sent_action = robot.send_action(teleop_action)

            if dataset is not None and not reset_triggered:
                if robot_is_moving and prev_observation_frame is not None:
                    # Shifted-frame logic during RT reset: C++ background thread controls
                    # the arm autonomously — Python does not send arm commands.
                    # Action = proprioception state from current obs (same keys as action_features:
                    # left/right TCP pose 9D + gripper 1D = 20D). Images and other obs keys are
                    # excluded because we iterate over robot.action_features, not current_observation.
                    current_as_action = {
                        k: current_observation[k]
                        for k in robot.action_features
                        if k in current_observation
                    }
                    action_frame = build_dataset_frame(
                        dataset.features, current_as_action, prefix=ACTION
                    )
                    frame = {
                        **prev_observation_frame,
                        **action_frame,
                        "task": single_task,
                    }
                    dataset.add_frame(frame)
                elif not robot_is_moving:
                    # Normal teleop: direct frame (obs[t], sent_action[t]).
                    action_frame = build_dataset_frame(
                        dataset.features, sent_action, prefix=ACTION
                    )
                    frame = {
                        **current_observation_frame,
                        **action_frame,
                        "task": single_task,
                    }
                    dataset.add_frame(frame)

            prev_observation_frame = current_observation_frame
            display_action = sent_action
        else:
            logger.info(
                "No policy or teleoperator provided, skipping action generation."
                "This is likely to happen when resetting the environment without a teleop device."
                "The robot won't be at its rest position at the start of the next episode."
            )

            _record_loop_sleep(
                start_loop_t=start_loop_t,
                fps=fps,
                start_episode_t=start_episode_t,
                robot=robot,
            )
            timestamp = time.perf_counter() - start_episode_t
            continue

        if display_data:
            log_rerun_data(observation=current_observation, action=display_action)

        _record_loop_sleep(
            start_loop_t=start_loop_t,
            fps=fps,
            start_episode_t=start_episode_t,
            robot=robot,
        )

        timestamp = time.perf_counter() - start_episode_t


def elite_cs66_rt_record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
):
    """Recording loop for Elite CS66 + SpaceMouse / Pico4.

    Mirrors the elite_cs66_rt_*_teleop_loop semantics:
    - Keyboard ``go_start`` or SpaceMouse both-buttons (rising edge) or Pico4
      A-button trigger ``robot.reset_to_initial_position()``.
    - While ``rt_moving`` is true the background servo trajectory owns the
      arm; Python skips ``send_action`` and records a shifted frame
      (previous observation + current-pose-as-action), matching the
      convention used by ``flexiv_rizon4_rt_record_loop``.
    - After the trajectory ends, the teleop's internal target is resynced to
      the robot's current TCP so the next send_action doesn't jump.
    """
    if dataset is not None and dataset.fps != fps:
        raise ValueError(
            f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps})."
        )
    if isinstance(teleop, list):
        raise ValueError("Multi-teleop mode is not supported for elite_cs66_rt.")

    teleop_name = teleop.name if isinstance(teleop, Teleoperator) else None

    timestamp = 0
    start_episode_t = time.perf_counter()
    prev_rt_moving = False
    prev_observation_frame = None
    both_buttons_prev = False

    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()
        reset_triggered = False
        refresh_listener_events(events)

        if events["stop_recording"]:
            logger.info("Stop recording requested, exiting record loop early")
            break
        if events["rerecord_episode"]:
            logger.info("Re-record episode requested, exiting record loop early")
            break
        if events["exit_early"]:
            events["exit_early"] = False
            logger.info("Exit early requested, exiting record loop early")
            break

        # Reset trigger sources: keyboard go_start, SpaceMouse both-buttons
        # rising edge, Pico4 A-button.
        trigger_reset = bool(events["go_start"])
        if isinstance(teleop, Teleoperator):
            if teleop_name == "spacemouse":
                both = (
                    teleop._spacemouse.is_left_button_pressed()
                    and teleop._spacemouse.is_right_button_pressed()
                )
                if both and not both_buttons_prev:
                    trigger_reset = True
                both_buttons_prev = both
            elif teleop_name == "pico4" and hasattr(teleop, "get_reset_button"):
                if teleop.get_reset_button():
                    trigger_reset = True

        if trigger_reset:
            events["go_start"] = False
            if hasattr(robot, "reset_to_initial_position"):
                try:
                    logger.info("Elite CS66 reset to initial position")
                    robot.reset_to_initial_position()
                    reset_triggered = True
                except Exception as e:
                    logger.error(f"Error during reset_to_initial_position: {e}")

        current_observation = robot.get_observation()
        current_observation_frame = None
        if dataset is not None:
            current_observation_frame = build_dataset_frame(
                dataset.features, current_observation, prefix=OBS_STR
            )

        robot_is_moving = hasattr(robot, "rt_moving") and robot.rt_moving
        if robot_is_moving:
            prev_rt_moving = True

        if prev_rt_moving and not robot_is_moving:
            prev_rt_moving = False
            try:
                _sync_elite_teleop_to_robot_pose(robot, teleop)
                logger.info("Synced teleop target to robot pose after reset")
            except Exception as e:
                logger.error(f"Failed to sync teleop after reset: {e}")

        if isinstance(teleop, Teleoperator):
            # SpaceMouse / Pico4 / Elite CS66 all share the unified
            # tcp.x/y/z + tcp.r1..r6 + gripper.pos schema — no conversion.
            teleop_action = teleop.get_action()

            if reset_triggered or robot_is_moving:
                sent_action = teleop_action  # not sent; for display only
            else:
                sent_action = robot.send_action(teleop_action)

            if dataset is not None and not reset_triggered:
                if robot_is_moving and prev_observation_frame is not None:
                    # Shifted-frame: action = current proprio so the dataset
                    # has something well-defined during the autonomous RT
                    # trajectory.
                    current_as_action = {
                        k: current_observation[k]
                        for k in robot.action_features
                        if k in current_observation
                    }
                    action_frame = build_dataset_frame(
                        dataset.features, current_as_action, prefix=ACTION
                    )
                    frame = {
                        **prev_observation_frame,
                        **action_frame,
                        "task": single_task,
                    }
                    dataset.add_frame(frame)
                elif not robot_is_moving:
                    action_frame = build_dataset_frame(
                        dataset.features, sent_action, prefix=ACTION
                    )
                    frame = {
                        **current_observation_frame,
                        **action_frame,
                        "task": single_task,
                    }
                    dataset.add_frame(frame)

            prev_observation_frame = current_observation_frame
            display_action = sent_action
        else:
            logger.info(
                "No teleoperator provided; recording observations only. "
                "The robot will stay at its current pose between episodes."
            )
            _record_loop_sleep(
                start_loop_t=start_loop_t,
                fps=fps,
                start_episode_t=start_episode_t,
                robot=robot,
            )
            timestamp = time.perf_counter() - start_episode_t
            continue

        if display_data:
            log_rerun_data(observation=current_observation, action=display_action)

        _record_loop_sleep(
            start_loop_t=start_loop_t,
            fps=fps,
            start_episode_t=start_episode_t,
            robot=robot,
        )

        timestamp = time.perf_counter() - start_episode_t


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    logger.info(pformat(asdict(cfg)))
    if cfg.display_data:
        init_rerun(session_name="recording", ip=cfg.display_ip, port=cfg.display_port)
    display_compressed_images = (
        True
        if (cfg.display_data and cfg.display_ip is not None and cfg.display_port is not None)
        else cfg.display_compressed_images
    )

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    teleop_type = cfg.teleop.type if cfg.teleop is not None else None
    use_raw_passthrough = _use_raw_passthrough_record(cfg.robot.type, teleop_type)

    if use_raw_passthrough:
        dataset_features = _build_raw_passthrough_dataset_features(robot, cfg.dataset.video)
    else:
        dataset_features = combine_feature_dicts(
            hw_to_dataset_features(robot.action_features, prefix=ACTION, use_video=cfg.dataset.video),
            hw_to_dataset_features(robot.observation_features, prefix=OBS_STR, use_video=cfg.dataset.video),
        )

    dataset = None
    listener = None

    try:
        if cfg.resume:
            dataset = LeRobotDataset(
                cfg.dataset.repo_id,
                root=cfg.dataset.root,
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
                streaming_encoding=cfg.dataset.streaming_encoding,
                encoder_queue_maxsize=cfg.dataset.encoder_queue_maxsize,
                encoder_threads=cfg.dataset.encoder_threads,
            )

            if hasattr(robot, "cameras") and len(robot.cameras) > 0:
                dataset.start_image_writer(
                    num_processes=cfg.dataset.num_image_writer_processes,
                    num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                )
            sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
        else:
            # Create empty dataset or load existing saved episodes
            sanity_check_dataset_name(cfg.dataset.repo_id)
            dataset = LeRobotDataset.create(
                cfg.dataset.repo_id,
                cfg.dataset.fps,
                root=cfg.dataset.root,
                robot_type=robot.name,
                features=dataset_features,
                use_videos=cfg.dataset.video,
                image_writer_processes=cfg.dataset.num_image_writer_processes,
                image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
                streaming_encoding=cfg.dataset.streaming_encoding,
                encoder_queue_maxsize=cfg.dataset.encoder_queue_maxsize,
                encoder_threads=cfg.dataset.encoder_threads,
            )

        # Vendor-specific robot.connect dispatch
        if teleop_type == "pico4" and cfg.robot.type == "flexiv_rizon4_rt":
            robot.connect(go_to_start=True)
            logger.info(f"Start EEF pose: {robot.get_current_tcp_pose_quat()}")
        elif (
            teleop_type == "bi_pico4"
            and cfg.robot.type == "bi_flexiv_rizon4_rt"
            and teleop is not None
        ):
            try:
                with ThreadPoolExecutor(max_workers=2) as executor:
                    robot_future = executor.submit(robot.connect, go_to_start=True)
                    teleop_future = executor.submit(teleop.pre_init)
                    teleop_future.result()
                    robot_future.result()
            except KeyboardInterrupt:
                logger.info("Startup interrupted by user")
                raise

            left_pose, right_pose = robot.get_current_tcp_pose_quat()
            logger.info(f"Left start pose:  {left_pose}")
            logger.info(f"Right start pose: {right_pose}")
        elif cfg.robot.type == "elite_cs66_rt" and teleop_type in ("spacemouse", "pico4"):
            robot.connect(go_to_start=True)
            start_obs = robot.get_observation()
            tcp_keys = [k for k in start_obs if k.startswith("tcp.")]
            logger.info(
                "Start pose: " + ", ".join(f"{k}={start_obs[k]:.6f}" for k in tcp_keys)
            )
        else:
            robot.connect()

        # Vendor-specific teleop.connect dispatch
        if teleop is not None:
            if teleop_type == "pico4" and cfg.robot.type == "flexiv_rizon4_rt":
                teleop.connect(current_tcp_pose_quat=robot.get_current_tcp_pose_quat())
                logger.info("Teleop initialized with robot EEF pose.")
            elif teleop_type == "bi_pico4" and cfg.robot.type == "bi_flexiv_rizon4_rt":
                left_pose, right_pose = robot.get_current_tcp_pose_quat()
                teleop.connect(left_tcp_pose_quat=left_pose, right_tcp_pose_quat=right_pose)
                logger.info("BiPico4 initialized with both robot EEF poses.")
            elif cfg.robot.type == "elite_cs66_rt" and teleop_type == "spacemouse":
                teleop.connect(current_tcp_pose_euler=robot.get_current_tcp_pose_euler())
                logger.info("Elite CS66 + SpaceMouse: teleop seeded from current TCP pose")
            elif cfg.robot.type == "elite_cs66_rt" and teleop_type == "pico4":
                teleop.connect(current_tcp_pose_quat=robot.get_current_tcp_pose_quat())
                logger.info("Elite CS66 + Pico4: teleop seeded from current TCP pose")
            else:
                teleop.connect()

        listener, events = init_keyboard_listener(teleop=teleop)

        if not cfg.dataset.streaming_encoding:
            logger.info(
                "Streaming encoding is disabled. If you have capable hardware, consider enabling it for way faster episode saving. --dataset.streaming_encoding=true --dataset.encoder_threads=2 # --dataset.vcodec=auto. More info in the documentation: https://huggingface.co/docs/lerobot/streaming_video_encoding"
            )

        with VideoEncodingManager(dataset):
            recorded_episodes = 0
            while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
                log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)

                # Dispatch the record loop by robot type
                if cfg.robot.type in ("xense_flare", "taccap_gripper"):
                    xense_flare_record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        dataset=dataset,
                        control_time_s=cfg.dataset.episode_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                    )
                elif cfg.robot.type == "elite_cs66_rt":
                    elite_cs66_rt_record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop=teleop,
                        dataset=dataset,
                        control_time_s=cfg.dataset.episode_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                    )
                elif cfg.robot.type in {"flexiv_rizon4_rt", "bi_flexiv_rizon4_rt"}:
                    flexiv_rizon4_rt_record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop=teleop,
                        dataset=dataset,
                        control_time_s=cfg.dataset.episode_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                    )
                else:
                    record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop=teleop,
                        dataset=dataset,
                        control_time_s=cfg.dataset.episode_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                        display_compressed_images=display_compressed_images,
                    )

                # Execute a few seconds without recording to give time to manually reset the environment
                # Skip reset for the last episode to be recorded
                if not events["stop_recording"] and (
                    (recorded_episodes < cfg.dataset.num_episodes - 1) or events["rerecord_episode"]
                ):
                    log_say("Reset the environment", cfg.play_sounds)

                    record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop=teleop,
                        control_time_s=cfg.dataset.reset_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                    )

                if events["rerecord_episode"]:
                    log_say("Re-record episode", cfg.play_sounds)
                    events["rerecord_episode"] = False
                    events["exit_early"] = False
                    dataset.clear_episode_buffer()
                    continue

                dataset.save_episode()
                recorded_episodes += 1
    finally:
        log_say("Stop recording", cfg.play_sounds, blocking=True)

        if dataset:
            dataset.finalize()

        if robot.is_connected:
            robot.disconnect()
        if teleop and teleop.is_connected:
            teleop.disconnect()

        if not is_headless() and listener:
            listener.stop()

        if cfg.dataset.push_to_hub:
            dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

        log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    register_third_party_plugins()
    record()


if __name__ == "__main__":
    main()
